Repository yufengliu15/cu-webring, pull requests merged in 2025-02, with the labels that each got.

#49 added yufeng website
  .github/auto-label.yml
  .github/workflows/auto-assign.yml
  .github/workflows/pull_request_template.md
  README.md
  index.html
  js/cu-webring.js
  js/user_sites.js
Labels: add-website, enhancement, documentation

#50 added bob joe
  .github/workflows/auto-assign.yml
  .github/workflows/auto-label.yml
  js/user_sites.js
Labels: add-website, enhancement, documentation

#53 PLEASE
  js/user_sites.js
Labels: add-website

#54 Site
  js/user_sites.js
Labels: add-website

#55 UI - Fixed css of bottom line of search bar
  css/style.css
Labels: enhancement

#56 UI - increase fade preloader
  css/style.css
Labels: enhancement

#59 UI
  js/user_sites.js
Labels: add-website

#62 Update user_sites.js
  js/user_sites.js
Labels: add-website

#64 Juan Marulanda
  js/user_sites.js
Labels: add-website

#65 aliases added
  .github/workflows/README.md
  README.md
  js/cu-webring.js
  js/user_sites.js
Labels: add-website, enhancement, documentation

#66 update the alias
  js/user_sites.js
Labels: add-website

#67 trying flags
  js/user_sites.js
Labels: add-website

#68 the last i promise
  js/user_sites.js
Labels: add-website

#70 Add user: Matteo Golin
  js/user_sites.js
Labels: add-website

#71 Add Neel Patel to webring
  js/user_sites.js
Labels: add-website

#72 Add Matthew MacRae-Bovell website
  js/user_sites.js
Labels: add-website

#73 add blog.rkempe.ca to user_sites.js
  js/user_sites.js
Labels: add-website

#75 Add Riyan Ahmed Website ✨
  js/user_sites.js
Labels: add-website

#76 Added Saim Hashmi
  js/user_sites.js
Labels: add-website

#77 Added Ansh
  js/user_sites.js
Labels: add-website

#78 Add Jeremy
  js/user_sites.js
Labels: add-website

#79 Fix
  js/user_sites.js
Labels: add-website

#81 Update domain for Jeremy
  js/user_sites.js
Labels: add-website

#82 add robertbabaev.tech + formatting from prettier
  js/user_sites.js
Labels: add-website

#83 Added personal website
  js/user_sites.js
Labels: add-website
